apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configmap
  namespace: oficina
  labels:
    app: oficina-api
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:8080"
  DbProvider: "PostgreSQL"
