apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: oficina
  labels:
    app: oficina-api
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres_password"
  POSTGRES_DB: "oficina"
  ConnectionStrings__DefaultConnection: "Host=postgres-service;Port=5432;Database=oficina;Username=postgres;Password=postgres_password"
  Jwt__Key: "MinhaChaveSuperSecretaDeAutenticacaoJWTFaseDoisTechChallenge2025!"
